CREATE TABLE IF NOT EXISTS DEPARTMENT(
    EMPLOYEE_ID TEXT,
    NAME TEXT,
    DEPARTMENT_ID TEXT,
    MANAGER_ID TEXT,
    SALARY REAL
    );
INSERT INTO DEPARTMENT (EMPLOYEE_ID, NAME, DEPARTMENT_ID, MANAGER_ID, SALARY) VALUES
    ('100', 'STEVEN KING','90', '100',24000),
    ('101', 'NEENA KOCHAR','90', '100',17000),
    ('102', 'LEX DEHAAN','90', '102',24000),
    ('103', 'BRUCE LEE','60', '103',9000),
    ('104', 'DIANA WILLS','60', '103',4800),
    ('105', 'VALLI PATOR','50', '100',25000),
    ('1973', 'LUV HAMI','60', '102',5000),
    ('106', 'DAVID AUSTIN','90', '100',6000),
SELECT DEPARTMENT_ID AS "Department Code",
COUNT(*) AS "No of Employees"
FROM DEPARTMENT
GROUP BY department id;

SELECT DEPARTMENT_ID, SUM(SALARY)
FROM DEPARTMENT 
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID AS "Department Code",
COUNT(*) AS "No of Employees",
SUM(salary) AS "Total Salary"
FROM DEPARTMENT 
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID AS "Department Code",
SUM(salary) AS "Total Salary"
FROM DEPARTMENT
WHERE MANAGER_ID ='103'
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, COUNT(*) AS "no. of employees"
FROM DEPARTMENT
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) >2;
